### ISSUE TITLE
Not an issue, but...

### ISSUE THREAD

**Issue by nbish11** [ins0/github-changelog-generator#2]
Just wandering if this project is actively maintained. This is the closest library that meets my needs, but there is definitely room for improvement. I would rather contribute directly to this project, than create my own.

**Comment by ins0** [comment]
Hey @nbish11, i created this little tool over a year ago. "actively maintained" is a bit off because i never  received enough attention that would indicate that something is missing or could be improved, so i didn't spend more time in this repository. It was just a tool that i hacked together to get a job done and i thought - make it open source then.

Feel free to send pull requests and send improvements, i will thankfully merge it. Thanks for asking in the first place!

**Comment by nbish11** [comment]
Awesome! Good to hear.
